[build]
target = "aarch64-unknown-linux-gnu" # Set the default target

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = [
    "-C", "link-args=--sysroot=/home/thebu/cpe442_lab2/sysroot",
    "-C", "link-args=-Wl,-rpath-link,/home/thebu/cpe442_lab2/sysroot"
]

